name: Nightly update
on:
  schedule:
    - cron: "16 22 * * *"
jobs:
  update-nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          version: 12
      - run: npm install octokit @octokit/action
      - run: node .github/actions/nightly-update.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
